[colors.bright]
black = "#555753"
blue = "#729FCF"
cyan = "#34E2E2"
green = "#8AE234"
magenta = "#AD7FA8"
red = "#EF2929"
white = "#EEEEEC"
yellow = "#FCE94F"

[colors.normal]
black = "#2E3436"
blue = "#3465A4"
cyan = "#06989A"
green = "#00CD00"
magenta = "#75507B"
red = "#CC0000"
white = "#D3D7CF"
yellow = "#C4A000"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "MesloLGS NF"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "="
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Alt"

# Disable Ctrl ++
[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "None"

# Disable Ctrl -
[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "None"

# Disable Ctrl =
[[keyboard.bindings]]
key = "="
mods = "Control"
action = "None"

# Shift+Return sends ESC+Enter to work in tmux
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
